# Generated by Django 5.0.1 on 2024-01-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0003_quistions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quistions',
            name='fourth_answer',
        ),
    ]
